V_SRC_DIR = /media/sf_shared
V_DST_DIR = ../

all:
	@echo "no default"
	
cv2:
	cp -r $(V_SRC_DIR)/wrx_v/ $(V_DST_DIR)

cb:
	cp wrx_map.mrp wrx_map_mrp.html $(V_SRC_DIR)
	cp wrx.syr wrx_syr.html $(V_SRC_DIR)
	cp wrx.twr wrx_twr.html $(V_SRC_DIR)
	cp wrx.twx $(V_SRC_DIR)
#	cp $(V_SRC_DIR)/wrx.bit $(V_SRC_DIR)/wrx.works.bit
	cp wrx.bit $(V_SRC_DIR)

cm:
	cp wrx_map.mrp wrx_map_mrp.html $(V_SRC_DIR)

cp:
	cp wrx.pwr $(V_SRC_DIR)

cc:
	cp wrx.xdc ../../../constrs_1/new

cc2:
	cp ../../../constrs_1/new/wrx.xdc wrx.new.xdc
	cp wrx.new.xdc $(V_SRC_DIR)
