KIWI_UI_LIST += "{ \"openwebrx\", 1 },"

FILES_EMBED += openwebrx/index.html openwebrx/openwebrx.css openwebrx/robots.txt
FILES_EMBED += openwebrx/openwebrx.js openwebrx/audio.js openwebrx/ima_adpcm.js

FILES_ALWAYS += $(subst web/,,$(wildcard web/openwebrx/gfx/*.jpg))
FILES_ALWAYS += $(subst web/,,$(wildcard web/openwebrx/gfx/*.png))
FILES_ALWAYS += $(subst web/,,$(wildcard web/openwebrx/icons/*.png))
FILES_ALWAYS += openwebrx/favicon.ico
FILES_ALWAYS += openwebrx/gfx/font-expletus-sans/ExpletusSans-Medium.ttf
#FILES_ALWAYS += openwebrx/openwebrx.ccomp.js
