#!/bin/sh
# wrapper for running the wrx app
# ./f runs the do_fft mode via +fft flag (see log notes)

# hack to see if we're running on a BBB
if test ! -f /etc/dogtag; then
	wrx.bin -gps -wrx +fft $*
	exit 0
fi

#DEV=wrx
#DEVID=cape-bone-${DEV}

DEV=SPIDEV0
DEVID=BB-${DEV}

DEV_PRU=wrx-P
DEVID_PRU=cape-bone-${DEV_PRU}

CAPE=${DEVID}-00A0
PRU=${DEVID_PRU}-00A0
SLOTS=`ls /sys/devices/bone_capemgr.*/slots`

if [ /lib/firmware/${CAPE}.dts -nt /lib/firmware/${CAPE}.dtbo ] ; then
	echo compile ${DEV} device tree;
	(cd /lib/firmware; dtc -O dtb -o ${CAPE}.dtbo -b 0 -@ ${CAPE}.dts);
# don't unload old slot because this is known to cause panics; must reboot
fi

if ! grep -q ${DEV} $SLOTS ; then
	echo load ${DEV} device tree;
	echo ${DEVID} > $SLOTS;
fi

if [ /lib/firmware/${PRU}.dts -nt /lib/firmware/${PRU}.dtbo ] ; then
	echo compile ${DEV_PRU} device tree;
	(cd /lib/firmware; dtc -O dtb -o ${PRU}.dtbo -b 0 -@ ${PRU}.dts);
# don't unload old slot because this is known to cause panics; must reboot
fi

if ! grep -q ${DEV_PRU} $SLOTS ; then
	echo load ${DEV_PRU} device tree;
	echo ${DEVID_PRU} > $SLOTS;
fi

wrx.bin -gps -wrx +fft $*
