// this file auto-generated by the e_cpu assembler -- edits will be overwritten

`ifndef _GEN_other_VH_
`define _GEN_other_VH_

// from assembler DEF directives:

//`define USE_OTHER    // DEFh 0x0

`endif
