$(OBJ_DIR_O3)/s4285convolutional.o: CFLAGS += -Ofast
$(OBJ_DIR_O3)/s4285demodulate.o: CFLAGS += -Ofast
$(OBJ_DIR_O3)/s4285interleaver.o: CFLAGS += -Ofast
$(OBJ_DIR_O3)/s4285kalman.o: CFLAGS += -Ofast
