FILES_EMBED += kiwi/kiwi.js kiwi/kiwi_util.js kiwi/w3_util.js
FILES_EMBED += kiwi/kiwi.css kiwi/w3_ext.css

FILES_EMBED += kiwi/admin.html kiwi/mfg.html
FILES_EMBED += kiwi/admin.js kiwi/mfg.js

FILES_ALWAYS += kiwi/pcb.jpg
