FILES_EMBED += kiwi/kiwi.js kiwi/kiwi_util.js kiwi/kiwi-data-demod.js

FILES_EMBED += kiwi/admin.html kiwi/gps.html kiwi/mfg.html
FILES_EMBED += kiwi/admin.js kiwi/gps.js kiwi/mfg.js

FILES_ALWAYS += kiwi/pcb.jpg
