if [ -f ~/.bashrc.local ]; then
  . ~/.bashrc.local
fi

alias ls="ls --color=auto"
alias la="ls -la"
alias lt="ls -lt"
alias j="jobs -l"
alias mo="more"
alias m="make"
alias m0="make OPT=O0"
alias mi="make install"
alias mc="make clean"
alias mcd="make clean_dist"
alias md="make debug"
alias ml="make log"
alias ms="make status"
alias mr="make restart"
alias mn="make -n"
alias mk="make -k"
alias mw="make --dry-run --debug=b"
alias d="dirs"
alias pd="pushd"
alias 2="pushd +2"
alias 3="pushd +3"
alias 4="pushd +4"
alias 5="pushd +5"
alias 6="pushd +6"
alias ic="ifconfig"
alias i="ic -a"
alias df="/bin/df -h"
alias g="function _g () { grep --color=auto -riI \$* . ; } ; _g"
alias g.="function _gdot () { grep --color=auto -iI \$* * ; } ; _gdot"
alias ff="function _ff () { find . -name \$* -print ; } ; _ff"
alias h="history"
alias z="suspend"
alias x="exit"
alias tr="traceroute"
alias al="alias"
alias soc="source ~/.profile"
alias pe="printenv"
alias ntp="/usr/lib/connman/test/set-global-timeservers pool.ntp.org"
alias cdp="cd \${PROJ}"
#alias dl="curl -o \${PROJ}.tgz www.jks.com/\${PROJ}/\${PROJ}.tgz"
#alias xt="cd ~; rm -rf \${PROJ} \${PROJ}.v*; tar xfz \${PROJ}.tgz; rm \${PROJ}.tgz; cdp"
alias jc="journalctl"
alias log="jc | tail -200"
alias pubip="curl ident.me; echo"
alias ident="curl ident.me; echo"
alias syc="systemctl --lines=100"
# error on Debian:
#alias pkgs="dpkg-query -W -f='${Installed-Size;8}\t${Status;1}\t${Package}\n' | grep -v '\sd\s' | sort -n | cut -f1,3-"
alias db="syc reload-or-restart dropbear.socket"
alias py="python"

# BBB
alias dog="more /etc/dogtag; uname -a"
alias tag="more /etc/dogtag; uname -a"
alias slots="cat /sys/devices/bone_capemgr.*/slots"
alias unslot="echo > /sys/devices/bone_capemgr.*/slots"
alias pins="more /sys/kernel/debug/pinctrl/44e10800.pinmux/pins"
alias pmux="more /sys/kernel/debug/pinctrl/44e10800.pinmux/pinmux-pins"

# KiwiSDR
alias kd="cdp; m stop; touch ~root/.kiwi_down; m start"
alias ku="cdp; m stop; rm -f ~root/.kiwi_down; m start"
alias mll="make leave"
alias vg="valgrind -v --track-origins=yes kiwi.bin"

# AIS
alias bbg="screen -h 1024 /dev/ttyUSB0 4800"
