if [ -f ~/.bashrc.local ]; then
  . ~/.bashrc.local
fi

alias ls="ls --color=auto"
alias la="ls -la"
alias lt="ls -lt"
alias j="jobs -l"
alias mo="more"
alias m="make"
alias mi="make install"
alias mc="make clean"
alias md="make debug"
alias ml="make log"
alias ms="make status"
alias mr="make restart"
alias mw="make --dry-run --debug=b"
alias sc="make rsync"
alias d="dirs"
alias pd="pushd"
alias p2="pushd +2"
alias p3="pushd +3"
alias p4="pushd +4"
alias ic="ifconfig"
alias i="ic -a"
alias df="/bin/df -h"
alias g="function _g () { grep --color=auto -riI \$* . ; } ; _g"
alias g.="function _gdot () { grep --color=auto -iI \$* * ; } ; _gdot"
alias ff="function _ff () { find . -name \$* -print ; } ; _ff"
alias slots="cat /sys/devices/bone_capemgr.*/slots"
alias unslot="echo > /sys/devices/bone_capemgr.*/slots"
alias pins="more /sys/kernel/debug/pinctrl/44e10800.pinmux/pins"
alias pmux="more /sys/kernel/debug/pinctrl/44e10800.pinmux/pinmux-pins"
alias h="history"
alias z="suspend"
alias x="exit"
alias tr="traceroute"
alias al="alias"
alias soc="source ~/.profile"
alias pe="printenv"
alias ntp="/usr/lib/connman/test/set-global-timeservers pool.ntp.org"
alias cdp="cd ~/\${PROJ}"
alias dl="curl -o \${PROJ}.tgz www.jks.com/\${PROJ}/\${PROJ}.tgz"
alias xt="cd ~; rm -rf \${PROJ} \${PROJ}.v*; tar xfz \${PROJ}.tgz; rm \${PROJ}.tgz; cdp"
alias jc="journalctl"
alias log="jc | tail -200"
alias pubip="curl ident.me; echo"
alias syc="systemctl --lines=100"
# error on Debian:
#alias pkgs="dpkg-query -W -f='${Installed-Size;8}\t${Status;1}\t${Package}\n' | grep -v '\sd\s' | sort -n | cut -f1,3-"
alias db="syc reload-or-restart dropbear.socket"

# 5370
alias clone="git clone git://github.com/jks-prv/5370_proc.git"
alias itest="cp /var/lib/cloud9/test_fixture.js /var/lib/cloud9/autorun/test_fixture.js"
alias utest="rm /var/lib/cloud9/autorun/test_fixture.js"

# wrx
alias wdown="cdp; m stop; touch /usr/local/.wrx_down; m start"
alias wup="cdp; m stop; rm -f /usr/local/.wrx_down; m start"
