FILES_EMBED += pkgs/w3.css pkgs/w3data.js
FILES_EMBED += $(subst web/,,$(wildcard web/pkgs/font-awesome-4.6.3/css/*))  $(subst web/,,$(wildcard web/pkgs/font-awesome-4.6.3/fonts/*))
FILES_EMBED += pkgs/cross-domain-local-storage/xd-utils.js pkgs/cross-domain-local-storage/xdLocalStorage.js
